### ISSUE TITLE
Controller, Service, etc. are not getting generated if entity has EmbeddedId

### ISSUE THREAD

**Issue by manishbhalshankar** [GuoGuang/generate-crud-code#2]
Hi @GuoGuang ,
The plugin is not generating any files except DTO if the entity has EmbeddedId instead.

**Comment by GuoGuang** [comment]
I've confirmed this bug and will consider supporting this in the near future

**Comment by GuoGuang** [comment]
I've already resolved the issue and released a fix version. Please upgrade to version 3.19 to address the problem.

Please note, if you have opted for the composite primary key approach, kindly remove ${id} from the Controller class and eliminate the @PathVariable annotation.
